"""1-day snapshot regression tests for the composable physics factories.

A tighter complement to the climatology-band ``test_*_model_default_statistics``
tests in ``model_test.py``: each test runs a 1-day aquaplanet at low resolution
and compares the final saved state of each prognostic field against a frozen
reference. Hardware order-of-operation differences (CPU/GPU/TPU XLA backends, and
even different CPU types within GitHub Actions' runner pool) perturb the float32
reductions, and the 1-day integration amplifies that into ~0.4-0.7% *pointwise*
drift — far too large for a pointwise ``assert_allclose`` to survive across
runners. The comparison therefore uses a per-field **normalized RMS** metric
(``||actual-ref||_2 / ||ref||_2``) with a 3% tolerance: the measured
cross-runner spread is <= 0.71% RMS, while a refactor that changes the
integration meaningfully moves a field by >> 1% RMS. See the ``RMS_RTOL`` note
below for the full rationale and measured numbers. For stricter, climate-scale
checks see ``test_speedy_model_default_statistics`` and
``test_echam_model_default_statistics``.

Reference snapshots in ``jcm/data/test/composable_physics_regression/`` are
regenerated by setting ``REGENERATE=1`` in the env::

    REGENERATE=1 JAX_PLATFORMS=cpu pytest jcm/physics/composable_physics_regression_test.py -v

Because the normalized-RMS metric tolerates the cross-runner spread, the
reference may be regenerated in any reasonable environment (a local CPU is fine);
it no longer has to match CI's exact jaxlib or be produced on a CI runner.
"""

from __future__ import annotations

import os
import unittest
from pathlib import Path

import numpy as np
import pytest

from jcm.forcing import ForcingData
from jcm.terrain import TerrainData
from jcm.utils import get_coords


REFERENCE_DIR = (
    Path(__file__).parent.parent / "data" / "test"
    / "composable_physics_regression"
)

# The snapshot comparison uses a per-field *normalized RMS* metric rather than a
# pointwise ``np.testing.assert_allclose``. WHY: GitHub Actions' ``ubuntu-latest``
# pool is hardware-heterogeneous (>=2 distinct CPU / XLA-codegen types observed),
# and the 1-day ECHAM integration is chaotic enough that the per-host
# floating-point difference amplifies into ~0.4-0.7% *pointwise* drift — with
# relative differences exploding past 200x at near-zero wind crossings. A
# pointwise rtol/atol check is therefore a coin-flip across runners: this is
# empirically why a gridpoint reference, even regenerated on a CI runner, could
# not be made to pass reliably (the runner that regenerates and the runner that
# validates are often different CPU types).
#
# The aggregate signal, by contrast, is tiny and stable. Measured between two
# real runners, the per-field ``||actual-ref||_2 / ||ref||_2`` is <= 0.71%
# (winds ~0.35-0.44%, specific humidity ~0.71%, temperature ~2e-5). A refactor
# that perturbs the integration *meaningfully* shifts a field by >> 1% RMS, so a
# 3% normalized-RMS threshold separates the two with ~4x margin while being
# immune to cross-runner reduction-order drift. Essentially-zero reference fields
# (e.g. unused condensate tracers) are checked absolutely instead, and every
# field must be finite. Because the metric tolerates the cross-runner spread, the
# reference no longer has to be generated on a CI runner or with CI's exact
# jaxlib — a local ``REGENERATE=1`` snapshot is valid.
RMS_RTOL = 0.03      # per-field normalized-RMS tolerance (see note above)
ZERO_ATOL = 1.0e-6   # abs RMS tolerance for fields whose reference is ~0


def _final_state_arrays(predictions):
    """Return the final-step nodal arrays we freeze as the reference fingerprint."""
    dyn = predictions.dynamics
    arrays = {
        "u_wind": np.asarray(dyn.u_wind[-1]),
        "v_wind": np.asarray(dyn.v_wind[-1]),
        "temperature": np.asarray(dyn.temperature[-1]),
        "specific_humidity": np.asarray(dyn.specific_humidity[-1]),
        "normalized_surface_pressure": np.asarray(
            dyn.normalized_surface_pressure[-1],
        ),
    }
    for name, tracer in dyn.tracers.items():
        arrays[f"tracer_{name}"] = np.asarray(tracer[-1])
    return arrays


def _check_or_regenerate(name: str, actual_arrays: dict) -> None:
    """Compare against the on-disk reference, or regenerate it.

    First-run / ``REGENERATE=1`` path writes the reference to disk and
    skips with a clear message — never silently auto-blesses output.
    Otherwise each field is compared with a normalized-RMS metric
    (``||actual-ref||_2 / ||ref||_2 <= RMS_RTOL``) that is robust to the
    cross-runner XLA reduction-order drift a pointwise check cannot
    tolerate (see the module note on ``RMS_RTOL``). Essentially-zero
    reference fields are checked absolutely, and all fields must be finite.
    """
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    path = REFERENCE_DIR / f"{name}.npz"

    if os.environ.get("REGENERATE") == "1" or not path.exists():
        np.savez(path, **actual_arrays)
        pytest.skip(
            f"Wrote reference at {path}; commit and rerun without "
            "REGENERATE=1 to verify against it.",
        )

    expected = np.load(path)
    expected_keys = set(expected.files)
    actual_keys = set(actual_arrays.keys())
    if expected_keys != actual_keys:
        raise AssertionError(
            f"Reference {path.name} field set drift: "
            f"only-in-reference={expected_keys - actual_keys}, "
            f"only-in-actual={actual_keys - expected_keys}. "
            "If this is intentional, regenerate with REGENERATE=1.",
        )
    for key in actual_arrays:
        actual = np.asarray(actual_arrays[key], dtype=np.float64)
        ref = np.asarray(expected[key], dtype=np.float64)
        if actual.shape != ref.shape:
            raise AssertionError(
                f"Reference {name!r} field {key!r} shape drift: "
                f"actual {actual.shape} vs reference {ref.shape}. "
                "If intentional, regenerate with REGENERATE=1.",
            )
        if not np.all(np.isfinite(actual)):
            raise AssertionError(
                f"Reference {name!r} field {key!r} has non-finite values.",
            )
        ref_rms = float(np.sqrt(np.mean(ref ** 2)))
        if ref_rms <= ZERO_ATOL:
            # Reference field is essentially zero (e.g. unused condensate
            # tracers): the actual must be ~zero too — any appreciable signal
            # is a real change, not reduction-order drift.
            actual_rms = float(np.sqrt(np.mean(actual ** 2)))
            if actual_rms > ZERO_ATOL:
                raise AssertionError(
                    f"Reference mismatch in {name!r} field {key!r}: reference "
                    f"is ~0 but actual RMS is {actual_rms:.3e} "
                    f"(> {ZERO_ATOL:.0e}). If intentional, regenerate with "
                    "REGENERATE=1 and commit.",
                )
            continue
        norm_rms = float(np.sqrt(np.mean((actual - ref) ** 2))) / ref_rms
        if norm_rms > RMS_RTOL:
            raise AssertionError(
                f"Reference mismatch in {name!r} field {key!r}: normalized RMS "
                f"difference {norm_rms:.3%} exceeds the {RMS_RTOL:.0%} tolerance "
                "(robust to cross-runner XLA drift, which is <=~0.7%). This "
                "indicates the refactor changed the integration meaningfully; "
                "if intentional, regenerate with REGENERATE=1 and commit.",
            )


class TestEchamReferenceTrajectory(unittest.TestCase):
    """T21L16 aquaplanet 1-day ECHAM reference trajectory (stretched grid).

    Reference lineage: regenerated 2026-07-04 for (a) the ECHAM ``physc``
    term reordering (radiation → vdiff → surface → convection → cloud):
    moving vdiff/surface before convection lets the Tiedtke zdqpbl closure
    read the SAME-STEP vdiff moisture tendency and delivered evaporation
    instead of a one-step-lagged supply (the lag compounded the
    convergence→convection feedback and NaN'd coupled T63L47 runs — onset7
    analysis), and the cloud schemes now see the post-vdiff ``thermo_run``;
    and (b) the vdiff moisture/hydrometeor matrix rows switching from the
    ICON-style dry-air mass to the moist Δp/g measure (ECHAM's ``zqdp``) so
    the delivered-E identity holds in the model's own dp/g budget
    convention (the dry-mass rows opened the composed column water budget
    by up to ~15 % of E in post-burst profiles). Both legitimately shift
    the 1-day integration, so the old fingerprint no longer applies.
    """

    @pytest.mark.slow
    def test_echam_default_reference(self):
        """Tolerance-based match for ``echam_physics()`` defaults."""
        from jcm.model import Model
        from jcm.physics.echam.echam_terms import echam_physics

        # Stretched 16-level sigma grid with a thin (~33 m) near-surface
        # layer. A uniform 8-level grid puts the lowest *full* level
        # ~500-600 m up, which is not a physical surface layer: over that
        # depth the dry-adiabatic potential-temperature offset (~5 K) makes
        # the surface layer read as strongly stable in bulk-Richardson terms
        # even over a warm ocean, so the faithful ECHAM ``echam_louis``
        # exchange coefficients suppress the surface fluxes and the
        # aquaplanet collapses to a near-dry state (q_max ~ 1e-6).
        #
        # Real ECHAM/ICON grids resolve the surface layer with thin
        # (tens-of-metres) near-surface layers. The quadratic stretch below
        # does the same: the lowest layer is ~33 m thick (lowest full level
        # ~16 m), so the adiabatic offset is ~0.2 K and the surface layer
        # reads ~neutral. ``echam_louis`` then produces a physically
        # sensible moist boundary layer (q_max ~ 4e-3). This makes the
        # reference a faithful target for the surface scheme rather than an
        # artefact of an over-coarse vertical grid.
        n_levels = 16
        xi = np.linspace(0.0, 1.0, n_levels + 1)
        sigma_boundaries = 1.0 - (1.0 - xi) ** 2  # dense near sigma=1 (surface)
        coords = get_coords(sigma_boundaries, nodal_shape=(64, 32))
        terrain = TerrainData.aquaplanet(coords)
        forcing = ForcingData.zeros((64, 32))

        # No time_step: ECHAM reports no stability limit, so the Model resolves
        # the 12-min no-limit default (matching run/default.yaml); the reference
        # was regenerated at that step (#751).
        model = Model(
            coords=coords,
            terrain=terrain,
            physics=echam_physics(),
        )
        preds = model.run(
            forcing=forcing,
            save_interval=1.0,
            total_time=1.0,
        )
        _check_or_regenerate(
            "echam_t21l16_1day", _final_state_arrays(preds),
        )


class TestSpeedyReferenceTrajectory(unittest.TestCase):
    """T21L8 aquaplanet 1-day SPEEDY reference trajectory."""

    @pytest.mark.slow
    def test_speedy_default_reference(self):
        """Tolerance-based match for ``speedy_physics()`` defaults."""
        from jcm.model import Model
        from jcm.physics.speedy.speedy_coords import get_speedy_coords
        from jcm.physics.speedy.speedy_terms import speedy_physics

        coords = get_speedy_coords(layers=8, spectral_truncation=21)
        terrain = TerrainData.aquaplanet(coords)
        forcing = ForcingData.zeros(coords.horizontal.nodal_shape)

        model = Model(
            coords=coords,
            terrain=terrain,
            physics=speedy_physics(),
        )
        preds = model.run(
            forcing=forcing,
            save_interval=1.0,
            total_time=1.0,
        )
        _check_or_regenerate(
            "speedy_t21l8_1day", _final_state_arrays(preds),
        )


if __name__ == "__main__":
    unittest.main()
