"""1-day snapshot regression tests for the composable physics factories.

A tighter complement to the climatology-band ``test_*_model_default_statistics``
tests in ``model_test.py``: each test runs a 1-day aquaplanet at low
resolution and compares the final saved state of each prognostic field
against a frozen reference with a tolerance picked to absorb hardware
order-of-operation drift (CPU vs GPU vs TPU XLA backends differ at the
ULP level on float32 reductions).

Tolerance is set to ``rtol=1e-3``, which catches any refactor that
perturbs the integration meaningfully while staying loose enough to
ignore reordered ops. Cross-hardware bit reproducibility is not
achievable; for stricter, climate-scale checks see
``test_speedy_model_default_statistics`` and
``test_echam_model_default_statistics``.

Reference snapshots in ``jcm/data/test/composable_physics_regression/``
are regenerated by setting ``REGENERATE=1`` in the env::

    REGENERATE=1 JAX_PLATFORMS=cpu pytest jcm/physics/composable_physics_regression_test.py -v
"""

from __future__ import annotations

import os
import unittest
from pathlib import Path

import numpy as np
import pytest

from jcm.forcing import ForcingData
from jcm.terrain import TerrainData
from jcm.utils import get_coords


REFERENCE_DIR = (
    Path(__file__).parent.parent / "data" / "test"
    / "composable_physics_regression"
)

# Tolerance for the snapshot comparison. Picked to absorb CPU↔GPU↔TPU
# XLA reduction-order drift while still catching refactors that perturb
# the integration meaningfully.
RTOL = 1e-3
ATOL = 1e-6


def _final_state_arrays(predictions):
    """Return the final-step nodal arrays we freeze as the reference fingerprint."""
    dyn = predictions.dynamics
    arrays = {
        "u_wind": np.asarray(dyn.u_wind[-1]),
        "v_wind": np.asarray(dyn.v_wind[-1]),
        "temperature": np.asarray(dyn.temperature[-1]),
        "specific_humidity": np.asarray(dyn.specific_humidity[-1]),
        "normalized_surface_pressure": np.asarray(
            dyn.normalized_surface_pressure[-1],
        ),
    }
    for name, tracer in dyn.tracers.items():
        arrays[f"tracer_{name}"] = np.asarray(tracer[-1])
    return arrays


def _check_or_regenerate(name: str, actual_arrays: dict) -> None:
    """Compare against the on-disk reference, or regenerate it.

    First-run / ``REGENERATE=1`` path writes the reference to disk and
    skips with a clear message — never silently auto-blesses output.
    Otherwise compares with ``np.testing.assert_allclose`` at
    ``rtol=RTOL``, ``atol=ATOL``.
    """
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    path = REFERENCE_DIR / f"{name}.npz"

    if os.environ.get("REGENERATE") == "1" or not path.exists():
        np.savez(path, **actual_arrays)
        pytest.skip(
            f"Wrote reference at {path}; commit and rerun without "
            "REGENERATE=1 to verify against it.",
        )

    expected = np.load(path)
    expected_keys = set(expected.files)
    actual_keys = set(actual_arrays.keys())
    if expected_keys != actual_keys:
        raise AssertionError(
            f"Reference {path.name} field set drift: "
            f"only-in-reference={expected_keys - actual_keys}, "
            f"only-in-actual={actual_keys - expected_keys}. "
            "If this is intentional, regenerate with REGENERATE=1.",
        )
    for key in actual_arrays:
        np.testing.assert_allclose(
            actual_arrays[key], expected[key],
            rtol=RTOL, atol=ATOL,
            err_msg=(
                f"Reference mismatch in {name!r} field {key!r}: "
                "the refactor changed numerics beyond the cross-hardware "
                f"tolerance ({RTOL=}, {ATOL=}). If intentional, regenerate "
                "with REGENERATE=1 and commit."
            ),
        )


class TestEchamReferenceTrajectory(unittest.TestCase):
    """T31L8 aquaplanet 1-day ECHAM reference trajectory."""

    @pytest.mark.slow
    def test_echam_default_reference(self):
        """Tolerance-based match for ``echam_physics()`` defaults."""
        from jcm.model import Model
        from jcm.physics.echam.echam_terms import echam_physics

        sigma_boundaries = np.linspace(0, 1, 9)  # 8 levels
        coords = get_coords(sigma_boundaries, nodal_shape=(64, 32))
        terrain = TerrainData.aquaplanet(coords)
        forcing = ForcingData.zeros((64, 32))

        model = Model(
            coords=coords,
            terrain=terrain,
            physics=echam_physics(),
        )
        preds = model.run(
            forcing=forcing,
            save_interval=1.0,
            total_time=1.0,
        )
        _check_or_regenerate(
            "echam_t31l8_1day", _final_state_arrays(preds),
        )


class TestSpeedyReferenceTrajectory(unittest.TestCase):
    """T21L8 aquaplanet 1-day SPEEDY reference trajectory."""

    @pytest.mark.slow
    def test_speedy_default_reference(self):
        """Tolerance-based match for ``speedy_physics()`` defaults."""
        from jcm.model import Model
        from jcm.physics.speedy.speedy_coords import get_speedy_coords
        from jcm.physics.speedy.speedy_terms import speedy_physics

        coords = get_speedy_coords(layers=8, spectral_truncation=21)
        terrain = TerrainData.aquaplanet(coords)
        forcing = ForcingData.zeros(coords.horizontal.nodal_shape)

        model = Model(
            coords=coords,
            terrain=terrain,
            physics=speedy_physics(),
        )
        preds = model.run(
            forcing=forcing,
            save_interval=1.0,
            total_time=1.0,
        )
        _check_or_regenerate(
            "speedy_t21l8_1day", _final_state_arrays(preds),
        )


if __name__ == "__main__":
    unittest.main()
