"""Tests for the packaged mirror manifest + its read-side view.

The manifest is the data-driven source of truth the typed resolver consults, so
these pin: that its ``is_published`` gate publishes exactly the intended
grid/level/vertical matrix, and that the packaged JSON matches what
``build_mirror.build_manifest`` regenerates (no stale hand edits) from the
``PUBLISHED_*`` sets declared there.
"""

import unittest

from jcm.data import mirror_manifest as mm
from jcm.data.mirror.build_mirror import (PUBLISHED_GRIDS, PUBLISHED_LEVELS,
                                          PUBLISHED_VERTICALS)


class TestManifestLoads(unittest.TestCase):
    def setUp(self):
        self.manifest = mm.load_manifest()

    def test_top_level_matches_published_sets(self):
        # The manifest's published sets are generated FROM build_mirror's
        # ``PUBLISHED_*`` declarations, so they carry the same grids/levels/
        # verticals (the Gaussian whitelist; the column ne30pg3 is extra).
        self.assertEqual(set(self.manifest["grids"]) & set(PUBLISHED_GRIDS),
                         set(PUBLISHED_GRIDS))
        self.assertEqual(set(self.manifest["levels"]), set(PUBLISHED_LEVELS))
        self.assertEqual(set(self.manifest["verticals"]),
                         set(PUBLISHED_VERTICALS))

    def test_auto_product_per_forcing_key(self):
        # macv2_file is intentionally absent: the MACv2-SP file is repo-packaged
        # (jcm.forcing.packaged_macv2_path), not a mirror product.
        for key, expected in (("emissions_file", "emissions_pd"),
                              ("dms_file", "dms"),
                              ("dust_file", "dust"),
                              ("oxidants_file", "oxidants_pd"),
                              ("ozone_file", "ozone_pd")):
            self.assertEqual(
                mm.product_for_key(self.manifest, key), expected, key)
        self.assertIsNone(mm.product_for_key(self.manifest, "macv2_file"))

    def test_bundle_path_fills_grid_and_level(self):
        self.assertEqual(
            mm.bundle_path(self.manifest, "emissions_pd", "t63"),
            "bundles/t63/emissions_pd.nc")
        self.assertEqual(
            mm.bundle_path(self.manifest, "oxidants_pd", "t106", 47),
            "bundles/t106_l47/oxidants_pd.nc")

    def test_yearly_products_carry_coverage(self):
        # The span actually staged on the mirror (verified via list_repo_files),
        # not the wider raw-source series — see build_mirror._MANIFEST_PRODUCTS.
        self.assertEqual(
            mm.coverage(self.manifest, "forcing_amip"), [1950, 2022])
        self.assertEqual(
            mm.coverage(self.manifest, "emissions_amip"), [1950, 2022])
        self.assertEqual(
            mm.coverage(self.manifest, "forcing_era5"), [1979, 2024])
        # Climatologies carry no coverage.
        self.assertIsNone(mm.coverage(self.manifest, "emissions_pd"))


class TestIsPublishedMatrix(unittest.TestCase):
    """``is_published`` over the grid/level/vertical matrix — its sole home.

    The manifest view is the ONE availability predicate (#751), so the matrix
    is pinned directly against the intended rule: a
    grid must be published (t63/t106); a level-resolved product (oxidants)
    additionally needs a published layer count AND a hybrid vertical (its bundle
    is on hybrid-level pressures); level-free products (emissions/dms/dust) are
    purely horizontal.
    """

    def _expected(self, product, grid, nlev, vertical):
        if grid not in ("t63", "t106"):
            return False
        if product == "oxidants_pd":
            return nlev in (47, 95) and vertical == "hybrid"
        return True

    def test_publication_matrix(self):
        manifest = mm.load_manifest()
        for product in ("emissions_pd", "dms", "dust", "oxidants_pd"):
            for grid in ("t42", "t63", "t106"):
                for nlev in (8, 47, 95):
                    for vertical in ("hybrid", "sigma"):
                        self.assertEqual(
                            mm.is_published(manifest, product, grid, nlev,
                                            vertical),
                            self._expected(product, grid, nlev, vertical),
                            (product, grid, nlev, vertical))


class TestManifestRegen(unittest.TestCase):
    def test_packaged_json_matches_builder(self):
        # The packaged JSON is generated by ``build_mirror.build_manifest`` —
        # assert they match so a mirror-table change that skips regeneration is
        # caught rather than shipping a stale manifest. Pass an empty staged
        # sidecar so the committed no-sidecar baseline (declared source coverage)
        # is reproduced regardless of any JCM_MIRROR_ROOT on the dev's machine.
        from jcm.data.mirror.build_mirror import build_manifest
        self.assertEqual(mm.load_manifest(),
                         build_manifest(staged_coverage={}))


class TestStagedCoverage(unittest.TestCase):
    """The staging sidecar (build_mirror) that pins ACTUAL yearly coverage.

    The transient ``{year}`` products declare the full-mirror span, but a partial
    ``--years`` run stages only a subset; the resolver pads the requested range by
    a year each side clipped to ``coverage``, so an over-advertised span would
    fetch a year file that was never built. The sidecar records what was staged
    and ``build_manifest`` folds it in.
    """

    def test_record_unions_and_build_manifest_folds(self):
        import tempfile
        from pathlib import Path

        from jcm.data.mirror import build_mirror as bm

        sidecar = Path(tempfile.mkdtemp()) / "staged_coverage.json"
        bm._record_staged_coverage(("forcing_amip", "ozone_amip"),
                                   1950, 2022, path=sidecar)
        # A later contiguous append widens the recorded span by union.
        bm._record_staged_coverage(("forcing_amip",), 1940, 2010, path=sidecar)
        staged = bm._load_staged_coverage(sidecar)
        self.assertEqual(staged["forcing_amip"], [1940, 2022])
        self.assertEqual(staged["ozone_amip"], [1950, 2022])

        man = bm.build_manifest(staged_coverage=staged)
        # Recorded products carry the staged span, not the source span.
        self.assertEqual(man["products"]["forcing_amip"]["coverage"],
                         [1940, 2022])
        self.assertEqual(man["products"]["ozone_amip"]["coverage"],
                         [1950, 2022])
        # An un-recorded transient product falls back to its declared
        # full-mirror span.
        self.assertEqual(man["products"]["emissions_amip"]["coverage"],
                         [1950, 2022])

    def test_adjacent_and_overlapping_appends_merge(self):
        import tempfile
        from pathlib import Path

        from jcm.data.mirror import build_mirror as bm

        sidecar = Path(tempfile.mkdtemp()) / "staged_coverage.json"
        bm._record_staged_coverage(("forcing_amip",), 1950, 1960, path=sidecar)
        # Adjacent (1961 touches 1960) and overlapping (1955-1975) both widen.
        bm._record_staged_coverage(("forcing_amip",), 1961, 1970, path=sidecar)
        bm._record_staged_coverage(("forcing_amip",), 1955, 1975, path=sidecar)
        self.assertEqual(
            bm._load_staged_coverage(sidecar)["forcing_amip"], [1950, 1975])

    def test_disjoint_append_raises_naming_the_gap(self):
        import tempfile
        from pathlib import Path

        from jcm.data.mirror import build_mirror as bm

        sidecar = Path(tempfile.mkdtemp()) / "staged_coverage.json"
        bm._record_staged_coverage(("forcing_amip",), 1950, 1960, path=sidecar)
        with self.assertRaises(ValueError) as cm:
            bm._record_staged_coverage(("forcing_amip",), 2000, 2010,
                                       path=sidecar)
        self.assertIn("1961-1999", str(cm.exception))
        # The rejected append leaves the sidecar untouched.
        self.assertEqual(
            bm._load_staged_coverage(sidecar)["forcing_amip"], [1950, 1960])

    def test_no_sidecar_falls_back_to_full_mirror_coverage(self):
        import tempfile
        from pathlib import Path

        from jcm.data.mirror import build_mirror as bm

        missing = Path(tempfile.mkdtemp()) / "absent.json"
        self.assertEqual(bm._load_staged_coverage(missing), {})
        man = bm.build_manifest(staged_coverage={})
        self.assertEqual(man["products"]["forcing_amip"]["coverage"],
                         [1950, 2022])


class TestRemoteCoverageVerification(unittest.TestCase):
    """The ``--verify-remote`` cross-check of the manifest vs. the mirror.

    Pins two things against a synthetic ``list_repo_files`` payload so drift
    between the committed manifest and the actual mirror is caught by a
    repeatable check, not manual inspection: the pure ``{year}`` path->span
    logic (:func:`remote_transient_coverage`, the class of bug that shipped a
    1870 source span the mirror never staged), and the static-artifact
    existence check (that every ``staged: true`` climatology/static variant is
    actually on the mirror, not merely advertised).
    """

    def _files(self, man, overrides=None):
        # Full mirror listing: every declared variant of every product staged
        # (transient over its declared coverage, static as a single file).
        # ``overrides`` maps a ``(product, grid, nlev)`` variant to a truncated
        # ``(lo, hi)`` span, an explicit ``set`` of years (to punch an interior
        # hole), or ``None`` to omit that variant entirely (never staged).
        from jcm.data.mirror.build_mirror import _product_variants
        overrides = overrides or {}
        files = []
        for name, rec in man["products"].items():
            if rec.get("source") == "packaged":
                continue  # shipped in the wheel, never on the mirror listing
            transient = "{year}" in rec["path"]
            if not transient and not rec["staged"]:
                continue
            for grid, nlev in _product_variants(rec):
                default = tuple(rec["coverage"]) if transient else "present"
                span = overrides.get((name, grid, nlev), default)
                if span is None:
                    continue
                if not transient:
                    files.append(mm.bundle_path(man, name, grid, nlev))
                    continue
                yrs = (sorted(span) if isinstance(span, (set, frozenset))
                       else range(span[0], span[1] + 1))
                path = rec["path"].replace("{grid}", grid)
                if nlev is not None:
                    path = path.replace("{nlev}", str(nlev))
                files += [path.replace("{year}", str(y)) for y in yrs]
        return files

    def test_span_derivation_matches_committed_manifest(self):
        from jcm.data.mirror.build_mirror import (_product_variants,
                                                  build_manifest,
                                                  remote_transient_coverage)
        man = build_manifest(staged_coverage={})
        coverage = remote_transient_coverage(self._files(man), man)
        # Every declared variant carries the full contiguous year list spanning
        # its declared coverage.
        for name, rec in man["products"].items():
            if "{year}" in rec["path"]:
                lo, hi = rec["coverage"]
                for variant in _product_variants(rec):
                    self.assertEqual(coverage[name][variant],
                                     list(range(lo, hi + 1)), (name, variant))

    def _drift(self, man, overrides):
        from jcm.data.mirror import build_mirror as bm

        files = self._files(man, overrides)

        class _FakeApi:
            def list_repo_files(self, *a, **k):
                return files

        import huggingface_hub
        orig = huggingface_hub.HfApi
        huggingface_hub.HfApi = _FakeApi
        try:
            return bm.verify_remote_coverage(manifest=man)
        finally:
            huggingface_hub.HfApi = orig

    def test_verify_remote_flags_truncated_variant(self):
        from jcm.data.mirror import build_mirror as bm

        man = bm.build_manifest(staged_coverage={})
        # t63 forcing_amip really holds only 1950-2000; every other variant is
        # complete. Drift must name the specific variant, not the whole product.
        drift = self._drift(man, {("forcing_amip", "t63", None): (1950, 2000)})
        self.assertEqual(drift, {"forcing_amip[t63]":
                                 {"manifest": [1950, 2022],
                                  "remote": [1950, 2000]}})

    def test_verify_remote_flags_interior_hole_with_intact_endpoints(self):
        from jcm.data.mirror import build_mirror as bm

        man = bm.build_manifest(staged_coverage={})
        # t63 forcing_amip keeps both endpoints (1950 & 2022) but 2000 is absent:
        # an endpoint-only span check passes; contiguity names the missing year.
        present = set(range(1950, 2023)) - {2000}
        drift = self._drift(man, {("forcing_amip", "t63", None): present})
        self.assertEqual(drift, {"forcing_amip[t63]":
                                 {"manifest": [1950, 2022],
                                  "remote": [1950, 2022],
                                  "missing": [2000]}})

    def test_verify_remote_flags_missing_variant_a_full_sibling_would_mask(self):
        from jcm.data.mirror import build_mirror as bm

        man = bm.build_manifest(staged_coverage={})
        # t106 forcing_amip is entirely absent while t63 is complete: pooling
        # would report no drift; per-variant names the missing grid.
        drift = self._drift(man, {("forcing_amip", "t106", None): None})
        self.assertEqual(drift, {"forcing_amip[t106]":
                                 {"manifest": [1950, 2022], "remote": None}})

    def test_verify_remote_clean_when_full_mirror(self):
        from jcm.data.mirror import build_mirror as bm

        man = bm.build_manifest(staged_coverage={})
        # A complete mirror (every transient AND static variant present) drifts
        # on nothing — the static existence check must not fire spuriously.
        self.assertEqual(self._drift(man, {}), {})

    def test_verify_remote_flags_missing_static_variant(self):
        from jcm.data.mirror import build_mirror as bm

        man = bm.build_manifest(staged_coverage={})
        # The t63 dms climatology is staged in the manifest but absent from the
        # mirror listing: the existence check names the exact variant instead of
        # letting the staged flag advertise a file the resolver would 404 on.
        drift = self._drift(man, {("dms", "t63", None): None})
        self.assertEqual(drift, {"dms[t63]":
                                 {"manifest": "bundles/t63/dms.nc",
                                  "remote": None}})


if __name__ == "__main__":
    unittest.main()
