"""Tests for the packaged mirror manifest + its read-side view.

The manifest is the data-driven source of truth the typed resolver consults, so
these pin: that it stays in sync with the ``jcm.data.bundle_names`` availability
predicate it generalises (they must never drift), that the packaged JSON matches
what ``build_mirror.build_manifest`` regenerates (no stale hand edits), and the
grid-free / not-yet-staged edge products (``macv2_sp``).
"""

import unittest

from jcm.data import bundle_names, mirror_manifest as mm


class TestManifestLoads(unittest.TestCase):
    def setUp(self):
        self.manifest = mm.load_manifest()

    def test_top_level_matches_published_sets(self):
        # The manifest's published sets are generated FROM bundle_names, so they
        # carry the same grids/levels/verticals.
        self.assertEqual(set(self.manifest["grids"]) & set(bundle_names.PUBLISHED_GRIDS),
                         set(bundle_names.PUBLISHED_GRIDS))
        self.assertEqual(set(self.manifest["levels"]),
                         set(bundle_names.PUBLISHED_LEVELS))
        self.assertEqual(set(self.manifest["verticals"]),
                         set(bundle_names.PUBLISHED_VERTICALS))

    def test_auto_product_per_forcing_key(self):
        for key, expected in (("emissions_file", "emissions_pd"),
                              ("dms_file", "dms"),
                              ("dust_file", "dust"),
                              ("oxidants_file", "oxidants_pd"),
                              ("ozone_file", "ozone_pd"),
                              ("macv2_file", "macv2_sp")):
            self.assertEqual(
                mm.product_for_key(self.manifest, key), expected, key)

    def test_bundle_path_fills_grid_and_level(self):
        self.assertEqual(
            mm.bundle_path(self.manifest, "emissions_pd", "t63"),
            "bundles/t63/emissions_pd.nc")
        self.assertEqual(
            mm.bundle_path(self.manifest, "oxidants_pd", "t106", 47),
            "bundles/t106_l47/oxidants_pd.nc")
        # A grid-free product ignores grid/nlev.
        self.assertEqual(
            mm.bundle_path(self.manifest, "macv2_sp"),
            "macv2_sp/MACv2.0-SP_v1.nc")

    def test_macv2_declared_but_not_staged(self):
        rec = mm.product(self.manifest, "macv2_sp")
        self.assertFalse(rec["staged"])
        self.assertIsNone(rec["grids"])       # grid-free
        self.assertIsNone(rec["coverage"])    # static

    def test_yearly_products_carry_coverage(self):
        # Transcribed from the forcing yamls (SOURCES.md).
        self.assertEqual(
            mm.coverage(self.manifest, "forcing_amip"), [1870, 2022])
        self.assertEqual(
            mm.coverage(self.manifest, "emissions_amip"), [1850, 2022])
        self.assertEqual(
            mm.coverage(self.manifest, "forcing_era5"), [1979, 2024])
        # Climatologies carry no coverage.
        self.assertIsNone(mm.coverage(self.manifest, "emissions_pd"))


class TestManifestMatchesBundleNames(unittest.TestCase):
    """``is_published`` must agree with the predicate it generalises."""

    _KEY_TO_PRODUCT = {"emissions_file": "emissions_pd", "dms_file": "dms",
                       "dust_file": "dust", "oxidants_file": "oxidants_pd"}

    def test_publication_matrix_agrees(self):
        manifest = mm.load_manifest()
        for key, product in self._KEY_TO_PRODUCT.items():
            for grid in ("t42", "t63", "t106"):
                for nlev in (8, 47, 95):
                    for vertical in ("hybrid", "sigma"):
                        self.assertEqual(
                            mm.is_published(manifest, product, grid, nlev,
                                            vertical),
                            bundle_names.bundle_is_published(
                                key, grid, nlev, vertical),
                            (key, grid, nlev, vertical))


class TestManifestRegen(unittest.TestCase):
    def test_packaged_json_matches_builder(self):
        # The packaged JSON is generated by ``build_mirror.build_manifest`` —
        # assert they match so a mirror-table change that skips regeneration is
        # caught rather than shipping a stale manifest.
        from jcm.data.mirror.build_mirror import build_manifest
        self.assertEqual(mm.load_manifest(), build_manifest())


if __name__ == "__main__":
    unittest.main()
