"""Heterogeneous mixed-phase freezing in the Lohmann 2M scheme: gradients and the
aerosol-free path (#953).

* ``het_mxphase_freezing`` (ECHAM-HAM's contact + immersion rates) is checked with
  ``jcm.testing.check_gradients`` inside the gate, and for finite reverse-mode
  derivatives at the singular points it guards: zero aerosol, zero TKE (the
  ``sqrt``), zero wet radius (the ``1/r`` of the diffusivities), a cold cell outside
  the gate (``exp(tmelt - T)``), zero liquid, and the gate's temperature edges.
* The aerosol-free path (no ``freezing_aerosol``: the DeMott (2010) closure) is
  pinned to its output at dev 8393799c, the commit before the ECHAM-HAM rates were
  wired in: ``lohmann_2m_aerosol_free_closure.npz`` holds the tendencies of
  ``cloud_microphysics_2m`` on the supercooled columns of the #953 Fortran fixture,
  generated by running this file as a script against that commit
  (``PYTHONPATH=<jcm @ 8393799c> python lohmann_2m_freezing_test.py --regenerate``).

The comparison with the compiled Fortran is ``lohmann_2m_freezing_reference_test.py``.
"""
from __future__ import annotations

import sys
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pytest

HERE = Path(__file__).resolve()
CLOSURE_REF = HERE.parents[2] / "data" / "test" / "lohmann_2m_aerosol_free_closure.npz"
FRZ_REF = HERE.parents[2] / "data" / "test" / "echam_cloud_reference" / "cloud2m_frz_T63L47.npz"
TEND_FIELDS = ("dtedt", "dqdt", "dqcdt", "dqidt", "dqncdt", "dqnidt")


def _het_args(n=4, **kw):
    """Return a gate column of n cells: supercooled liquid with dust and BC, TKE cooling."""
    base = dict(
        freezing_condition=jnp.ones((n,), bool), pressure=jnp.full((n,), 6.0e4),
        tke=jnp.full((n,), 0.1), vertical_velocity=jnp.zeros((n,)),
        cloud_cover=jnp.full((n,), 0.5), bc_soluble_fraction=jnp.full((n,), 0.1),
        bc_insoluble_fraction=jnp.full((n,), 0.3), dust_soluble_fraction=jnp.full((n,), 0.2),
        dust_accumulation_fraction=jnp.full((n,), 0.15), dust_coarse_fraction=jnp.full((n,), 0.05),
        air_density=jnp.full((n,), 0.8), inv_air_density=jnp.full((n,), 1.25),
        wet_radius_aitken=jnp.full((n,), 3e-8), wet_radius_accumulation=jnp.full((n,), 2e-7),
        wet_radius_coarse=jnp.full((n,), 1.2e-6),
        temperature=jnp.array([266.0, 256.0, 248.0, 243.0])[:n],
        min_cdnc=jnp.full((n,), 4e7), ice_crystal_number=jnp.full((n,), 1e4),
        droplet_number=jnp.full((n,), 8e7), freezing_rate=jnp.zeros((n,)),
        cloud_ice=jnp.full((n,), 1e-6), cloud_liquid=jnp.full((n,), 2e-4))
    base.update(kw)
    return base


_DIFF = ("tke", "bc_soluble_fraction", "dust_soluble_fraction", "dust_accumulation_fraction",
         "dust_coarse_fraction", "wet_radius_accumulation", "wet_radius_coarse", "temperature",
         "ice_crystal_number", "droplet_number", "cloud_liquid", "cloud_ice", "cloud_cover")


def _het(params, dt=720.0):
    from jcm.physics.clouds.lohmann_2m.deposition_freezing import het_mxphase_freezing

    def f(diff, fixed):
        return het_mxphase_freezing(**fixed, **diff, timestep=dt,
                                    min_liquid_threshold=params.cqtmin, params=params)
    return f


def test_het_mxphase_freezing_gradients_match_differences():
    """Forward and reverse mode against a central difference inside the gate, float64.

    The cells are where neither of ECHAM's caps binds (the frozen mass at the liquid,
    F 2809; the frozen number at the droplets above the floor, F 2819): at 243 K and below
    immersion freezes nearly all liquid and both are kinks, where a central difference
    averages the two one-sided slopes. Finiteness there is the singular-point test's.
    ``rtol`` 1e-3: per input the AD derivative converges on the difference to 1e-8, but
    the black-carbon immersion coefficient is 1e4 times dust's, so the difference along
    ``bc_soluble_fraction`` carries round-off of ~1e-4 of the projection.
    """
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    from jcm.testing import check_gradients
    with jax.enable_x64(True):
        p = CloudParams2M.default()
        a = jax.tree_util.tree_map(lambda x: jnp.asarray(x, jnp.float64 if x.dtype != bool else bool),
                                   _het_args(temperature=jnp.array([266.0, 258.0, 252.0, 249.0])))
        diff = {k: a.pop(k) for k in _DIFF}
        f = _het(p)
        check_gradients(lambda d: f(d, a), (diff,), rtol=1e-3,
                        live_inputs=("['dust_soluble_fraction']", "['tke']",
                                     "['dust_accumulation_fraction']", "['cloud_liquid']"))


def test_het_mxphase_freezing_gradient_through_immersion_coefficients():
    """The immersion coefficients are live differentiable parameters."""
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    from jcm.physics.clouds.lohmann_2m.deposition_freezing import het_mxphase_freezing
    a = _het_args()

    def loss(cdu, cbc):
        p = CloudParams2M.default(immersion_coefficient_dust=cdu, immersion_coefficient_bc=cbc)
        return jnp.sum(het_mxphase_freezing(**a, timestep=720.0, min_liquid_threshold=p.cqtmin,
                                            params=p)[2])
    g = jax.grad(loss, argnums=(0, 1))(32.3, 2.91e-3)
    assert all(np.isfinite(float(x)) and float(x) > 0.0 for x in g)


@pytest.mark.parametrize("case", ["no_aerosol", "no_tke", "no_radius", "cold_outside_gate",
                                  "no_liquid", "gate_edges"])
def test_het_mxphase_freezing_reverse_mode_finite_at_singular_points(case):
    """Every reverse-mode derivative is finite where the guarded operations are singular."""
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    p = CloudParams2M.default()
    zero = jnp.zeros((4,))
    kw = {
        "no_aerosol": dict(bc_soluble_fraction=zero, bc_insoluble_fraction=zero,
                           dust_soluble_fraction=zero, dust_accumulation_fraction=zero,
                           dust_coarse_fraction=zero),
        "no_tke": dict(tke=zero),
        "no_radius": dict(wet_radius_aitken=zero, wet_radius_accumulation=zero,
                          wet_radius_coarse=zero),
        "cold_outside_gate": dict(temperature=jnp.array([180.0, 190.0, 200.0, 230.0]),
                                  freezing_condition=jnp.zeros((4,), bool)),
        "no_liquid": dict(cloud_liquid=zero, droplet_number=jnp.full((4,), 1e-12),
                          freezing_condition=jnp.zeros((4,), bool)),
        "gate_edges": dict(temperature=jnp.array([238.16, 238.2, 273.1, 273.14])),
    }[case]
    a = _het_args(**kw)
    diff = {k: a.pop(k) for k in _DIFF}
    f = _het(p)
    g = jax.grad(lambda d: sum(jnp.sum(x) for x in f(d, a)))(diff)
    for k, v in g.items():
        assert bool(jnp.all(jnp.isfinite(v))), (case, k)


# ---------------------------------------------------------------------------
# the aerosol-free path is dev's
# ---------------------------------------------------------------------------
def _closure_tendencies():
    """Run cloud_microphysics_2m on the supercooled fixture columns WITHOUT freezing_aerosol,
    float64, jcm's own constants and default CloudParams2M (dt720 inputs).
    """
    from jcm.physics.clouds.lohmann_2m.scheme import cloud_microphysics_2m
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    import jcm.constants as c
    with np.load(FRZ_REF) as z:
        d = {k[3:]: z[k] for k in z.files if k.startswith("in/")}
        rho = z["diag/dt720/rho"]
    dt = 720.0
    p = CloudParams2M.default()
    dz = np.diff(d["paphm1"], axis=0) / (rho * c.grav)

    def one(T, q, qc, qi, qnc, qni, cf, r, dz_, tke, pr):
        zero = jnp.zeros_like(T)
        return cloud_microphysics_2m(T, q, pr, qc, qi, qnc, qni, cf, r, dz_, tke, zero, zero,
                                     zero, jnp.asarray(dt, T.dtype), p)[0]

    args = [d["ptm1"], d["pqm1"], d["pxlm1"], d["pxim1"], d["xtm1_cdnc"], d["xtm1_icnc"],
            d["paclc"], rho, dz, d["ptkem1"], d["papm1"]]
    with jax.enable_x64(True):
        t = jax.vmap(one, in_axes=1, out_axes=1)(*[jnp.asarray(x, jnp.float64) for x in args])
        return {k: np.asarray(getattr(t, k)) for k in TEND_FIELDS}


def test_aerosol_free_closure_unchanged():
    """Without freezing_aerosol the scheme computes what dev 8393799c computed, to
    round-off, in supercooled cells where the DeMott closure freezes droplets.
    """
    ref = np.load(CLOSURE_REF)
    got = _closure_tendencies()
    assert np.max(np.abs(ref["dqnidt"])) > 0.0
    for k in TEND_FIELDS:
        np.testing.assert_allclose(got[k], ref[k], rtol=1e-12,
                                   atol=1e-12 * float(np.max(np.abs(ref[k]))), err_msg=k)


if __name__ == "__main__" and "--regenerate" in sys.argv:   # pragma: no cover
    import jcm
    out = _closure_tendencies()
    np.savez_compressed(CLOSURE_REF, **out)
    print("wrote", CLOSURE_REF, "with jcm from", jcm.__file__)
