"""Heterogeneous mixed-phase freezing in the Lohmann 2M scheme: gradients and the
aerosol-free path (#953).

* ``het_mxphase_freezing`` (ECHAM-HAM's contact + immersion rates) is checked with
  ``jcm.testing.check_gradients`` inside the gate, and for finite reverse-mode
  derivatives at the singular points it guards: zero aerosol, zero TKE (the
  ``sqrt``), zero wet radius (the ``1/r`` of the diffusivities), a cold cell outside
  the gate (``exp(tmelt - T)``), zero liquid, and the gate's temperature edges.
* The aerosol-free path (no ``freezing_aerosol``: the DeMott (2010) closure) is
  pinned to its output at dev 2dc609fd, which has the closure but not the ECHAM-HAM
  rates: ``lohmann_2m_aerosol_free_closure.npz`` holds the tendencies of
  ``cloud_microphysics_2m`` on the supercooled columns of the #953 Fortran fixture,
  generated by running this file as a script against that commit
  (``PYTHONPATH=<jcm @ 2dc609fd> python lohmann_2m_freezing_test.py --regenerate``).

The comparison with the compiled Fortran is ``lohmann_2m_freezing_reference_test.py``.
"""
from __future__ import annotations

import sys
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pytest

HERE = Path(__file__).resolve()
CLOSURE_REF = HERE.parents[2] / "data" / "test" / "lohmann_2m_aerosol_free_closure.npz"
FRZ_REF = HERE.parents[2] / "data" / "test" / "echam_cloud_reference" / "cloud2m_frz_T63L47.npz"
TEND_FIELDS = ("dtedt", "dqdt", "dqcdt", "dqidt", "dqncdt", "dqnidt")


def _het_args(n=4, **kw):
    """Return a gate column of n cells: supercooled liquid with dust and BC, TKE cooling."""
    base = dict(
        freezing_condition=jnp.ones((n,), bool), pressure=jnp.full((n,), 6.0e4),
        tke=jnp.full((n,), 0.1), vertical_velocity=jnp.zeros((n,)),
        cloud_cover=jnp.full((n,), 0.5), bc_soluble_fraction=jnp.full((n,), 0.1),
        bc_insoluble_fraction=jnp.full((n,), 0.3), dust_soluble_fraction=jnp.full((n,), 0.2),
        dust_accumulation_fraction=jnp.full((n,), 0.15), dust_coarse_fraction=jnp.full((n,), 0.05),
        air_density=jnp.full((n,), 0.8), inv_air_density=jnp.full((n,), 1.25),
        wet_radius_aitken=jnp.full((n,), 3e-8), wet_radius_accumulation=jnp.full((n,), 2e-7),
        wet_radius_coarse=jnp.full((n,), 1.2e-6),
        temperature=jnp.array([266.0, 256.0, 248.0, 243.0])[:n],
        min_cdnc=jnp.full((n,), 4e7), ice_crystal_number=jnp.full((n,), 1e4),
        droplet_number=jnp.full((n,), 8e7), freezing_rate=jnp.zeros((n,)),
        cloud_ice=jnp.full((n,), 1e-6), cloud_liquid=jnp.full((n,), 2e-4))
    base.update(kw)
    return base


_DIFF = ("tke", "bc_soluble_fraction", "dust_soluble_fraction", "dust_accumulation_fraction",
         "dust_coarse_fraction", "wet_radius_accumulation", "wet_radius_coarse", "temperature",
         "ice_crystal_number", "droplet_number", "cloud_liquid", "cloud_ice", "cloud_cover")


def _het(params, dt=720.0):
    from jcm.physics.clouds.lohmann_2m.deposition_freezing import het_mxphase_freezing

    def f(diff, fixed):
        return het_mxphase_freezing(**fixed, **diff, timestep=dt,
                                    min_liquid_threshold=params.cqtmin, params=params)
    return f


def test_het_mxphase_freezing_gradients_match_differences():
    """Forward and reverse mode against a central difference inside the gate, float64.

    The cells are where neither of ECHAM's caps binds (the frozen mass at the liquid,
    F 2809; the frozen number at the droplets above the floor, F 2819): at 243 K and below
    immersion freezes nearly all liquid and both are kinks, where a central difference
    averages the two one-sided slopes. Finiteness there is the singular-point test's.
    ``rtol`` 1e-3: per input the AD derivative converges on the difference to 1e-8, but
    the black-carbon immersion coefficient is 1e4 times dust's, so the difference along
    ``bc_soluble_fraction`` carries round-off of ~1e-4 of the projection.
    """
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    from jcm.testing import check_gradients
    with jax.enable_x64(True):
        p = CloudParams2M.default()
        a = jax.tree_util.tree_map(lambda x: jnp.asarray(x, jnp.float64 if x.dtype != bool else bool),
                                   _het_args(temperature=jnp.array([266.0, 258.0, 252.0, 249.0])))
        diff = {k: a.pop(k) for k in _DIFF}
        f = _het(p)
        check_gradients(lambda d: f(d, a), (diff,), rtol=1e-3,
                        live_inputs=("['dust_soluble_fraction']", "['tke']",
                                     "['dust_accumulation_fraction']", "['cloud_liquid']"))


def test_het_mxphase_freezing_gradient_through_immersion_coefficients():
    """The immersion coefficients are live differentiable parameters."""
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    from jcm.physics.clouds.lohmann_2m.deposition_freezing import het_mxphase_freezing
    a = _het_args()

    def loss(cdu, cbc):
        p = CloudParams2M.default(immersion_coefficient_dust=cdu, immersion_coefficient_bc=cbc)
        return jnp.sum(het_mxphase_freezing(**a, timestep=720.0, min_liquid_threshold=p.cqtmin,
                                            params=p)[2])
    g = jax.grad(loss, argnums=(0, 1))(32.3, 2.91e-3)
    assert all(np.isfinite(float(x)) and float(x) > 0.0 for x in g)


def test_het_mxphase_freezing_follows_the_parameter_melting_point_and_gravity():
    """The rates take tmelt and grav from the parameter set, as the 6.2 gate does.

    Immersion freezing scales as exp(tmelt - T) and as the TKE cooling's g, so at a
    warm supercooled cell (266 K, small frozen fraction) raising ``params.tmelt`` by
    1 K multiplies it by about e, and doubling ``params.grav`` by about 2; the
    derivatives with respect to both are live.
    """
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    from jcm.physics.clouds.lohmann_2m.deposition_freezing import het_mxphase_freezing
    a = _het_args(n=1, temperature=jnp.array([266.0]), bc_soluble_fraction=jnp.zeros((1,)),
                  bc_insoluble_fraction=jnp.zeros((1,)), dust_accumulation_fraction=jnp.zeros((1,)),
                  dust_coarse_fraction=jnp.zeros((1,)))
    base = CloudParams2M.default()

    def frozen(tmelt, grav):
        p = CloudParams2M.default(tmelt=tmelt, grav=grav)
        return het_mxphase_freezing(**a, timestep=720.0, min_liquid_threshold=p.cqtmin,
                                    params=p)[2][0]
    t0, g0 = float(base.tmelt), float(base.grav)
    ref = float(frozen(t0, g0))
    assert ref > 0.0
    np.testing.assert_allclose(float(frozen(t0 + 1.0, g0)) / ref, np.e, rtol=1e-2)
    np.testing.assert_allclose(float(frozen(t0, 2.0 * g0)) / ref, 2.0, rtol=1e-2)
    d_tmelt, d_grav = jax.grad(frozen, argnums=(0, 1))(t0, g0)
    assert float(d_tmelt) > 0.0 and float(d_grav) > 0.0


@pytest.mark.parametrize("case", ["no_aerosol", "no_tke", "no_radius", "cold_outside_gate",
                                  "no_liquid", "gate_edges"])
def test_het_mxphase_freezing_reverse_mode_finite_at_singular_points(case):
    """Every reverse-mode derivative is finite where the guarded operations are singular."""
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    p = CloudParams2M.default()
    zero = jnp.zeros((4,))
    kw = {
        "no_aerosol": dict(bc_soluble_fraction=zero, bc_insoluble_fraction=zero,
                           dust_soluble_fraction=zero, dust_accumulation_fraction=zero,
                           dust_coarse_fraction=zero),
        "no_tke": dict(tke=zero),
        "no_radius": dict(wet_radius_aitken=zero, wet_radius_accumulation=zero,
                          wet_radius_coarse=zero),
        "cold_outside_gate": dict(temperature=jnp.array([180.0, 190.0, 200.0, 230.0]),
                                  freezing_condition=jnp.zeros((4,), bool)),
        "no_liquid": dict(cloud_liquid=zero, droplet_number=jnp.full((4,), 1e-12),
                          freezing_condition=jnp.zeros((4,), bool)),
        "gate_edges": dict(temperature=jnp.array([238.16, 238.2, 273.1, 273.14])),
    }[case]
    a = _het_args(**kw)
    diff = {k: a.pop(k) for k in _DIFF}
    f = _het(p)
    g = jax.grad(lambda d: sum(jnp.sum(x) for x in f(d, a)))(diff)
    for k, v in g.items():
        assert bool(jnp.all(jnp.isfinite(v))), (case, k)


# ---------------------------------------------------------------------------
# the aerosol-free path is dev's
# ---------------------------------------------------------------------------
def _closure_tendencies():
    """Run cloud_microphysics_2m on the supercooled fixture columns WITHOUT freezing_aerosol,
    float64, jcm's own constants and default CloudParams2M except ``ccsaut = 900``, the
    value the reference was generated with, so the closure is compared at fixed
    parameters (dt720 inputs).
    """
    from jcm.physics.clouds.lohmann_2m.scheme import cloud_microphysics_2m
    from jcm.physics.clouds.lohmann_2m_params import CloudParams2M
    import jcm.constants as c
    with np.load(FRZ_REF) as z:
        d = {k[3:]: z[k] for k in z.files if k.startswith("in/")}
        rho = z["diag/dt720/rho"]
    dt = 720.0
    p = CloudParams2M.default(ccsaut=900.0)
    dz = np.diff(d["paphm1"], axis=0) / (rho * c.grav)

    def one(T, q, qc, qi, qnc, qni, cf, r, dz_, tke, pr):
        zero = jnp.zeros_like(T)
        return cloud_microphysics_2m(T, q, pr, qc, qi, qnc, qni, cf, r, dz_, tke, zero, zero,
                                     zero, jnp.asarray(dt, T.dtype), p)[0]

    args = [d["ptm1"], d["pqm1"], d["pxlm1"], d["pxim1"], d["xtm1_cdnc"], d["xtm1_icnc"],
            d["paclc"], rho, dz, d["ptkem1"], d["papm1"]]
    with jax.enable_x64(True):
        t = jax.vmap(one, in_axes=1, out_axes=1)(*[jnp.asarray(x, jnp.float64) for x in args])
        return {k: np.asarray(getattr(t, k)) for k in TEND_FIELDS}


def test_aerosol_free_closure_unchanged():
    """Without freezing_aerosol the scheme computes what dev 2dc609fd computed, to
    round-off, in supercooled cells where the DeMott closure freezes droplets.
    """
    ref = np.load(CLOSURE_REF)
    got = _closure_tendencies()
    assert np.max(np.abs(ref["dqnidt"])) > 0.0
    for k in TEND_FIELDS:
        np.testing.assert_allclose(got[k], ref[k], rtol=1e-12,
                                   atol=1e-12 * float(np.max(np.abs(ref[k]))), err_msg=k)


# ---------------------------------------------------------------------------
# the JAM -> 2M hand-off, at the level of the physics terms
# ---------------------------------------------------------------------------
_NLEV, _NCOLS, _DT = 6, 2, 720.0


def _term_inputs():
    """Return a supercooled, dusty, turbulent column pair for the 2M physics term."""
    from types import SimpleNamespace

    from jcm.physics.aerosol.aerosol_types import AerosolData
    from jcm.physics.clouds.cloud_data import CloudData
    from jcm.physics.clouds.lohmann_2m.types import HeterogeneousFreezingAerosol
    from jcm.physics.convection.saturation import saturation_specific_humidity
    from jcm.physics_interface import PhysicsState

    shape = (_NLEV, _NCOLS)
    col = lambda v: jnp.asarray(v)[:, None] * jnp.ones((1, _NCOLS))  # noqa: E731
    pressure = col(np.linspace(4.5e4, 7.0e4, _NLEV))
    temperature = col(np.linspace(240.0, 262.0, _NLEV))
    humidity = saturation_specific_humidity(temperature, pressure, phase="water")
    rho = pressure / (287.05 * temperature)
    qc = jnp.full(shape, 1e-4)
    clouds = CloudData.zeros((_NCOLS,), _NLEV).copy(
        cloud_fraction=jnp.full(shape, 0.5), qc=qc, qi=jnp.zeros(shape),
        conv_detrainment_qc=jnp.zeros(shape), conv_detrainment_qi=jnp.zeros(shape))
    state = PhysicsState.zeros(
        shape, temperature=temperature, specific_humidity=humidity,
        tracers={"qc": qc, "qi": jnp.zeros(shape), "qnc": 8e7 / rho, "qni": jnp.zeros(shape)})
    diagnostics = {
        "_dt_seconds": _DT, "pressure_full": pressure, "air_density": rho,
        "layer_thickness": jnp.full(shape, 400.0), "clouds": clouds,
        "aerosol": AerosolData.zeros((_NCOLS,), _NLEV),
        "vertical_diffusion": SimpleNamespace(tke=jnp.full(shape, 0.1)),
        "activated_cdnc": jnp.full(shape, 8e7),
    }
    fa = HeterogeneousFreezingAerosol(
        dust_soluble=jnp.full(shape, 0.3), dust_insoluble_accumulation=jnp.zeros(shape),
        dust_insoluble_coarse=jnp.zeros(shape), bc_soluble=jnp.full(shape, 0.1),
        bc_insoluble=jnp.full(shape, 0.3), wet_radius_insoluble_aitken=jnp.full(shape, 3e-8),
        wet_radius_insoluble_accumulation=jnp.zeros(shape),
        wet_radius_insoluble_coarse=jnp.zeros(shape))
    return state, diagnostics, fa


def test_2m_term_freezes_with_the_published_freezing_aerosol():
    """``Lohmann2MMicrophysics`` reads ``diagnostics["freezing_aerosol"]``: its tendencies
    change with it, and equal the column function called with the same struct.
    """
    from jcm.physics.clouds.lohmann_2m import Lohmann2MMicrophysics
    from jcm.physics.clouds.lohmann_2m.scheme import cloud_microphysics_2m
    state, diagnostics, fa = _term_inputs()
    term = Lohmann2MMicrophysics()
    p = term.params.get_value()
    without, _ = term(state, diagnostics, None, None)
    with_fa, _ = term(state, {**diagnostics, "freezing_aerosol": fa}, None, None)
    gap = jnp.max(jnp.abs(with_fa.tracers["qni"] - without.tracers["qni"]))
    assert float(gap) > 1e3, float(gap)
    clouds = diagnostics["clouds"]
    # The term's inputs are ECHAM's: the anchor is the received state (no carried
    # post-physics state here), the increments are zero, and the air density is the
    # anchor's virtual density with the layer depth that keeps the layer mass.
    import jcm.constants as consts
    virtual_temperature = state.temperature * (
        1.0 + consts.vtmpc1 * state.specific_humidity
        - (state.tracers["qc"] + state.tracers["qi"]))
    rho = diagnostics["pressure_full"] / (consts.rd * virtual_temperature)
    dz = diagnostics["air_density"] * diagnostics["layer_thickness"] / rho
    for j in range(_NCOLS):
        c = lambda x: x[:, j]  # noqa: E731
        direct = cloud_microphysics_2m(
            c(state.temperature), c(state.specific_humidity), c(diagnostics["pressure_full"]),
            c(state.tracers["qc"]), c(state.tracers["qi"]),
            c(state.tracers["qnc"]), c(state.tracers["qni"]),
            c(clouds.cloud_fraction), c(rho), c(dz), c(diagnostics["vertical_diffusion"].tke),
            c(diagnostics["activated_cdnc"]), jnp.zeros(_NLEV), jnp.zeros(_NLEV), _DT, p,
            freezing_aerosol=jax.tree_util.tree_map(c, fa))[0]
        for name, got, want in (("qni", with_fa.tracers["qni"], direct.dqnidt),
                                ("qi", with_fa.tracers["qi"], direct.dqidt),
                                ("T", with_fa.temperature, direct.dtedt)):
            np.testing.assert_allclose(np.asarray(got[:, j]), np.asarray(want),
                                       rtol=1e-5, atol=1e-14, err_msg=name)


def test_jam_publishes_freezing_aerosol_before_the_cloud_scheme():
    """In the ECHAM composition the JAM term that publishes the freezing inputs runs
    ahead of the 2M term that reads them (same step, not the carry's previous value).
    """
    from jcm.physics.aerosol.jam.ice_nucleation.ice_term import IceNucleation
    from jcm.physics.clouds.lohmann_2m import Lohmann2MMicrophysics
    from jcm.physics.echam.echam_terms import echam_physics
    terms = echam_physics(aerosol_module="jam", cloud_scheme="2m",
                          jam_microphysics="placeholder").terms
    kinds = [type(t) for t in terms]
    assert kinds.index(IceNucleation) < kinds.index(Lohmann2MMicrophysics)
    assert "freezing_aerosol" in terms[kinds.index(IceNucleation)].provides


if __name__ == "__main__" and "--regenerate" in sys.argv:   # pragma: no cover
    import jcm
    out = _closure_tendencies()
    np.savez_compressed(CLOSURE_REF, **out)
    print("wrote", CLOSURE_REF, "with jcm from", jcm.__file__)
